//----------------------------------------------
//
//         Sketch Generated by Visuino
//               www.visuino.com
//           Version 8.0.0.167
//
//------------------ Source --------------------
//
// W02 Lab.visuino
//
//----------------------------------------------

#define __V_REFF_ 5.0f
#define VISUINO_ARDUINO_NANO

#include <OpenWire.h>
#include <Mitov.h>
#include <Mitov_StandardBreakSerial.h>
#include <Mitov_ArduinoBasicDigitalInputChannel.h>
#include <Mitov_ArduinoBasicDigitalInputOutputChannel.h>
#include <Mitov_ArduinoBasicDigitalChannel.h>
#include <Mitov_ArduinoBasicDigitalPWMChannel.h>
#include <Mitov_UltrasonicRanger.h>
#include <Mitov_Math.h>
#include <Mitov_BinaryGenerators.h>
#include <Mitov_BasicGenerator.h>


// Shared Component Member Variables

namespace ComponentVariables
{
class
{
public:
  uint32_t Value2 : 3;
  bool Value1 : 1;
  bool Value3 : 1;
  bool Value4 : 1;
  bool Value5 : 1;
  bool Value6 : 1;
  bool Value7 : 1;

} BitFields;

class Variable2
{
public:
  inline static uint32_t GetValue() { return BitFields.Value2; }
  inline static void SetValue( uint32_t AValue ) { BitFields.Value2 = AValue; }

};

class Variable1
{
public:
  inline static bool GetValue() { return BitFields.Value1; }
  inline static void SetValue( bool AValue ) { BitFields.Value1 = AValue; }

};

class Variable3
{
public:
  inline static bool GetValue() { return BitFields.Value3; }
  inline static void SetValue( bool AValue ) { BitFields.Value3 = AValue; }

};

class Variable4
{
public:
  inline static bool GetValue() { return BitFields.Value4; }
  inline static void SetValue( bool AValue ) { BitFields.Value4 = AValue; }

};

class Variable5
{
public:
  inline static bool GetValue() { return BitFields.Value5; }
  inline static void SetValue( bool AValue ) { BitFields.Value5 = AValue; }

};

class Variable6
{
public:
  inline static bool GetValue() { return BitFields.Value6; }
  inline static void SetValue( bool AValue ) { BitFields.Value6 = AValue; }

};

class Variable7
{
public:
  inline static bool GetValue() { return BitFields.Value7; }
  inline static void SetValue( bool AValue ) { BitFields.Value7 = AValue; }

};

} // ComponentVariables

// Arduino Constant Declarations

namespace VisuinoConstants
{
class FloatValue3
{
public:
    inline static constexpr float GetValue() { return 1000; }
};

class FloatValue0
{
public:
    inline static constexpr float GetValue() { return 10000; }
};

class FloatValue1
{
public:
    inline static constexpr float GetValue() { return 100; }
};

class FloatValue2
{
public:
    inline static constexpr float GetValue() { return 0; }
};

} // VisuinoConstants

// Pin Call Declarations

namespace PinCalls
{
class PinCallerReceive0
{
public:
  void Notify( void *_Data );

};
class PinCallerReceive1
{
public:
  void Notify( void *_Data );

};
class PinCallerReceive2
{
public:
  void Notify( void *_Data );

};
class PinCallerReceive3
{
public:
  void Notify( void *_Data );

};
} // PinCalls

// Call Chains

namespace CallChains
{
class GetPeriod1
{
public:
  inline static constexpr uint32_t Count() { return 0; }
  inline static void Call( int32_t AIndex, unsigned long & APeriod ) {}

};
class PeriodicCall1
{
public:
  inline static constexpr uint32_t Count() { return 0; }
  static void Call();

};
} // CallChains

// System Objects Declarations

namespace BoardDeclarations
{
Mitov::TPeriodMicros<5000, ::CallChains::PeriodicCall1> SystemPeriodMicros_5000;
} // BoardDeclarations

// Arduino Board Declarations

namespace BoardDeclarations
{
namespace Types
{
typedef Mitov::ArduinoBasicDigitalPWMChannel<
  Mitov::ConstantProperty<9, bool, false >, // AnalogInputPin_o_IsConnected = False
  Mitov::ConstantProperty<4, bool, true >, // AutoConfig = True (Default)
  Mitov::ConstantProperty<2, bool, true >, // DigitalInputPin_o_IsConnected = True
  Mitov::ConstantProperty<3, bool, false >, // InitialValue = False (Default)
  Mitov::ConstantProperty<10, bool, false >, // IsAnalog = False (Default)
  Mitov::ConstantProperty<5, bool, false >, // IsOutput = False (Default)
  Mitov::ConstantProperty<6, bool, false >, // IsPullUp = False (Default)
  Mitov::ConstantProperty<123, bool, false >, // IsRawInput = 0
  Mitov::DigitalPin_NoImplementation<7 >, // OutputPin
  false, // OutputPin_Board_Connected_
  3 // PIN_DIGITAL
   > TArduinoBasicDigitalPWMInterruptChannel1;
} // Types

namespace Instances
{
Types::TArduinoBasicDigitalPWMInterruptChannel1 TArduinoBasicDigitalPWMInterruptChannel1;
} // Instances

namespace Types
{
typedef Mitov::ArduinoBasicDigitalChannel<
  Mitov::ConstantProperty<4, bool, true >, // AutoConfig = True (Default)
  Mitov::ConstantProperty<2, bool, true >, // DigitalInputPin_o_IsConnected = True
  Mitov::ConstantProperty<3, bool, false >, // InitialValue = False (Default)
  Mitov::ConstantProperty<5, bool, false >, // IsOutput = False (Default)
  Mitov::ConstantProperty<6, bool, false >, // IsPullUp = False (Default)
  Mitov::ConstantProperty<123, bool, true >, // IsRawInput = -1
  Mitov::DigitalPin_NoImplementation<7 >, // OutputPin
  false, // OutputPin_Board_Connected_
  4 // PIN_DIGITAL
   > TArduinoAdditionalDigitalChannel1;
} // Types

namespace Instances
{
Types::TArduinoAdditionalDigitalChannel1 TArduinoAdditionalDigitalChannel1;
} // Instances

namespace Types
{
typedef Mitov::ArduinoBasicDigitalPWMChannel<
  Mitov::ConstantProperty<9, bool, false >, // AnalogInputPin_o_IsConnected = False
  Mitov::ConstantProperty<4, bool, true >, // AutoConfig = True (Default)
  Mitov::ConstantProperty<2, bool, true >, // DigitalInputPin_o_IsConnected = True
  Mitov::ConstantProperty<3, bool, false >, // InitialValue = False (Default)
  Mitov::ConstantProperty<10, bool, false >, // IsAnalog = False (Default)
  Mitov::ConstantProperty<5, bool, false >, // IsOutput = False (Default)
  Mitov::ConstantProperty<6, bool, false >, // IsPullUp = False (Default)
  Mitov::ConstantProperty<123, bool, true >, // IsRawInput = -1
  Mitov::DigitalPin_NoImplementation<7 >, // OutputPin
  false, // OutputPin_Board_Connected_
  9 // PIN_DIGITAL
   > TArduinoBasicDigitalPWMChannel1;
} // Types

namespace Instances
{
Types::TArduinoBasicDigitalPWMChannel1 TArduinoBasicDigitalPWMChannel1;
} // Instances

namespace Types
{
typedef Mitov::ArduinoBasicDigitalPWMChannel<
  Mitov::ConstantProperty<9, bool, false >, // AnalogInputPin_o_IsConnected = False
  Mitov::ConstantProperty<4, bool, true >, // AutoConfig = True (Default)
  Mitov::ConstantProperty<2, bool, false >, // DigitalInputPin_o_IsConnected = False
  Mitov::ConstantProperty<3, bool, false >, // InitialValue = False (Default)
  Mitov::ConstantProperty<10, bool, false >, // IsAnalog = False (Default)
  Mitov::ConstantProperty<5, bool, false >, // IsOutput = False (Default)
  Mitov::ConstantProperty<6, bool, false >, // IsPullUp = False (Default)
  Mitov::ConstantProperty<123, bool, false >, // IsRawInput = 0
  Mitov::DigitalPin_EmbeddedPinImplementation<7, ::PinCalls::PinCallerReceive0 >, // OutputPin
  true, // OutputPin_Board_Connected_
  10 // PIN_DIGITAL
   > TArduinoBasicDigitalPWMChannel2;
} // Types

namespace Instances
{
Types::TArduinoBasicDigitalPWMChannel2 TArduinoBasicDigitalPWMChannel2;
} // Instances

namespace Types
{
typedef Mitov::BreakSerialPort<
  HardwareSerial, // 0_SERIAL_TYPE
  Serial, // 1_C_OBJECT
  Mitov::ConstantProperty<4, uint32_t, 0 >, // AfterSendingDelay = 0 (Default)
  Mitov::ConstantProperty<7, uint32_t, 8 >, // DataBits = 8 (Default)
  Mitov::EmbeddedCallChain<CallChains::GetPeriod1 >, // Elements_GetPeriod
  Mitov::ConstantProperty<2, bool, true >, // Enabled = True (Default)
  Mitov::ConstantProperty<17, uint32_t, 0 >, // FElementIndex = 0
  Mitov::ConstantProperty<21, uint32_t, 0 >, // FEndTime = 0
  Mitov::ConstantProperty<23, bool, false >, // FInBreak = False
  Mitov::ConstantProperty<19, bool, false >, // FSending = False
  Mitov::GenericPin_NoImplementation<5 >, // OutputPin
  Mitov::ConstantProperty<9, Mitov::TArduinoStandardSerialParity, Mitov::spNone >, // Parity = 0 (Default)
  Mitov::NestedProperty<16, Mitov::TArduinoSerialBreak<
    Mitov::ConstantProperty<11, bool, false >, // Enabled = False (Default)
    Mitov::NestedProperty<15, Mitov::TAurduinoEnableValue<
      Mitov::ConstantProperty<13, bool, false >, // Enabled = False (Default)
      Mitov::ConstantProperty<14, uint32_t, 100 > // Value = 100 (Default)
       > > // Period
     > >, // SendBreak
  Mitov::DigitalPin_NoImplementation<3 >, // SendingOutputPin
  Mitov::ConstantProperty<6, uint32_t, 9600 >, // Speed = 9600 (Default)
  Mitov::ConstantProperty<8, uint32_t, 1 >, // StopBits = 1 (Default)
  Mitov::ConstantProperty<87, uint32_t, 1 > // TXPin
   > SerialPort0;
} // Types

namespace Instances
{
Types::SerialPort0 SerialPort0;
} // Instances

} // BoardDeclarations

// Declarations

namespace Declarations
{
namespace Types
{
typedef Mitov::ArduinoSerialInput<BoardDeclarations::Types::SerialPort0, BoardDeclarations::Instances::SerialPort0, float> SerialPort0_Input_IOWFloatStream_1;
} // Types

namespace Instances
{
Types::SerialPort0_Input_IOWFloatStream_1 SerialPort0_Input_IOWFloatStream_1;
} // Instances

namespace Types
{
typedef Mitov::UltrasonicRanger<
  Mitov::ConstantProperty<5, bool, true >, // ClockInputPin_o_IsConnected = True
  Mitov::ConstantProperty<7, bool, true >, // Enabled = True (Default)
  Mitov::TypedVariable<15, bool, ::ComponentVariables::Variable1 >, // FClocked
  Mitov::TypedVariable<17, uint32_t, ::ComponentVariables::Variable2 >, // FState
  Mitov::AnalogPin_EmbeddedPinImplementation<3, ::PinCalls::PinCallerReceive1 >, // OutputPin
  Mitov::ConstantProperty<12, uint32_t, 100 >, // PauseTime = 100 (Default)
  Mitov::DigitalPin_DirectBoardPinImplementation<9 >, // PingOutputPin
  Mitov::ConstantProperty<11, uint32_t, 2 >, // PingTime = 2 (Default)
  Mitov::ConstantProperty<9, uint32_t, 100 >, // Timeout = 100 (Default)
  Mitov::DigitalPin_NoImplementation<6 >, // TimeoutOutputPin
  Mitov::ConstantPropertyFloat<10, float, ::VisuinoConstants::FloatValue0 >, // TimeoutValue = 10000 (Default)
  Mitov::ConstantProperty<8, Mitov::TArduinoRangerUnits, Mitov::rdCm > // Units = 0 (Default)
   > UltrasonicRanger1; // TArduinoUltrasonicRanger
} // Types

namespace Instances
{
Types::UltrasonicRanger1 UltrasonicRanger1; // TArduinoUltrasonicRanger
} // Instances

namespace Types
{
typedef Mitov::CompareValue<
  Mitov::CompareType_Implementation_ctSmallerOrEqual, // CompareType = 5
  Mitov::ConstantProperty<4, bool, true >, // Enabled = True (Default)
  Mitov::TypedVariable<8, bool, ::ComponentVariables::Variable3 >, // FStarted
  Mitov::DigitalPin_EmbeddedPinImplementation<5, ::PinCalls::PinCallerReceive2 >, // OutputPin
  float, // TYPE
  Mitov::ConstantPropertyFloat<7, float, ::VisuinoConstants::FloatValue1 > // Value = 100
   > Compare1; // TArduinoCompareValue
} // Types

namespace Instances
{
Types::Compare1 Compare1 = Types::Compare1( 0.0f ); // TArduinoCompareValue
} // Instances

namespace Types
{
typedef Mitov::PulseGenerator_Shared<
  Mitov::ConstantPropertyFloat<8, float, ::VisuinoConstants::FloatValue2 >, // Asymmetry = 0 (Default)
  Mitov::ConstantProperty<6, bool, true >, // Enabled = True (Default)
  Mitov::ConstantPropertyFloat<17, float, ::VisuinoConstants::FloatValue2>, // FPhase = 0
  Mitov::TypedVariable<15, bool, ::ComponentVariables::Variable4 >, // FValue
  Mitov::ConstantPropertyFloat<7, float, ::VisuinoConstants::FloatValue1 >, // Frequency = 100
  Mitov::ConstantProperty<4, bool, false >, // InitialValue = False (Default)
  Mitov::DigitalPin_EmbeddedPinImplementation<3, ::PinCalls::PinCallerReceive3 >, // OutputPin
  Mitov::ConstantPropertyFloat<9, float, ::VisuinoConstants::FloatValue2 >, // Phase = 0 (Default)
  Mitov::NestedProperty<14, Mitov::TArduinoGeneratorWhenDisabled<
    Mitov::ConstantProperty<13, bool, false >, // CompleteCycle = False (Default)
    Mitov::ConstantProperty<12, bool, true >, // FCycleCompleted = True
    Mitov::ConstantProperty<11, bool, false > // Reset = False (Default)
     > > // WhenDisabled
   > PulseGenerator1; // TArduinoPulseGenerator
} // Types

namespace Instances
{
Types::PulseGenerator1 PulseGenerator1; // TArduinoPulseGenerator
} // Instances

namespace Types
{
typedef Mitov::PulseGenerator<
  Mitov::ConstantPropertyFloat<8, float, ::VisuinoConstants::FloatValue2 >, // Asymmetry = 0 (Default)
  Mitov::TypedVariableValue<6, bool, ::ComponentVariables::Variable5, true >, // Enabled = True (Default)
  Mitov::ConstantPropertyFloat<17, float, ::VisuinoConstants::FloatValue2>, // FPhase = 0
  Mitov::TypedVariable<15, bool, ::ComponentVariables::Variable6 >, // FValue
  Mitov::ConstantPropertyFloat<7, float, ::VisuinoConstants::FloatValue3 >, // Frequency = 1000
  Mitov::ConstantProperty<4, bool, true >, // InitialValue = True
  Mitov::DigitalPin_DirectBoardPinImplementation<4 >, // OutputPin
  Mitov::ConstantPropertyFloat<9, float, ::VisuinoConstants::FloatValue2 >, // Phase = 0 (Default)
  Mitov::NestedProperty<14, Mitov::TArduinoGeneratorWhenDisabled<
    Mitov::ConstantProperty<13, bool, false >, // CompleteCycle = False (Default)
    Mitov::ConstantProperty<12, bool, true >, // FCycleCompleted = True
    Mitov::ConstantProperty<11, bool, false > // Reset = False (Default)
     > > // WhenDisabled
   > PulseGenerator; // TArduinoPulseGenerator
} // Types

namespace Instances
{
Types::PulseGenerator PulseGenerator; // TArduinoPulseGenerator
} // Instances

} // Declarations

// Type Converters

namespace TypeConverters
{
Mitov::Convert_BinaryToClock<Mitov::TypedVariable<0, bool, ::ComponentVariables::Variable7 > > Converter0;
} // TypeConverters

// Bindings

namespace Bindings
{
inline void PulseGenerator_EnabledInputPin_o_Receive( void * ___PTR___, bool __AOriginalValue__ )
{
  bool ___A_VALUE___ = *(bool *)___PTR___;
  if( __AOriginalValue__ == ___A_VALUE___ )
    return;

  Declarations::Instances::PulseGenerator.Enabled() = ___A_VALUE___;
  Declarations::Instances::PulseGenerator.UpdateEnabled();
}

} // Bindings

// Call Chains

namespace CallChains
{
void PeriodicCall1::Call()
{
  Declarations::Instances::PulseGenerator1.PeriodicCall();
}

} // CallChains

// Pin Call Declarations

namespace PinCalls
{
void PinCallerConverterReceive1( void *_Data );
} // PinCalls

// Pin Call Implementations

namespace PinCalls
{
void PinCallerReceive0::Notify( void *_Data )
{
  Declarations::Instances::UltrasonicRanger1.EchoInputPin_o_Receive( _Data );
}

void PinCallerReceive1::Notify( void *_Data )
{
  Declarations::Instances::SerialPort0_Input_IOWFloatStream_1.InputPin_o_Receive( _Data );
  Declarations::Instances::Compare1.InputPin_o_Receive( _Data );
}

void PinCallerReceive2::Notify( void *_Data )
{
  bool __Value_PulseGenerator_EnabledInputPin__ = Declarations::Instances::PulseGenerator.Enabled().GetValue();
  ::Bindings::PulseGenerator_EnabledInputPin_o_Receive( _Data, __Value_PulseGenerator_EnabledInputPin__ );
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMInterruptChannel1.DigitalInputPin_o_Receive( _Data );
}

void PinCallerReceive3::Notify( void *_Data )
{
  TypeConverters::Converter0.Convert( _Data, PinCallerConverterReceive1 );
}

void PinCallerConverterReceive1( void *_Data )
{
  Declarations::Instances::UltrasonicRanger1.ClockInputPin_o_Receive( _Data );
}
} // PinCalls

namespace ComponentsHardware
{
void SystemUpdateHardware()
{
}
} // ComponentsHardware

//The setup function is called once at startup of the sketch
void setup()
{
  BoardDeclarations::Instances::SerialPort0.SystemInit();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMInterruptChannel1.SystemInit();
  BoardDeclarations::Instances::TArduinoAdditionalDigitalChannel1.SystemInit();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMChannel1.SystemInit();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMChannel2.SystemInit();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMInterruptChannel1.SystemStart();
  BoardDeclarations::Instances::TArduinoAdditionalDigitalChannel1.SystemStart();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMChannel2.SystemStart();
  Declarations::Instances::UltrasonicRanger1.SystemStart();
  Declarations::Instances::Compare1.SystemStart();
  Declarations::Instances::PulseGenerator1.SystemStart();
  Declarations::Instances::PulseGenerator.SystemStart();
  BoardDeclarations::SystemPeriodMicros_5000.SystemStarted();
}

// The loop function is called in an endless loop
void loop()
{
  BoardDeclarations::SystemPeriodMicros_5000.SystemLoopBegin();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMInterruptChannel1.SystemLoopBegin();
  BoardDeclarations::Instances::TArduinoAdditionalDigitalChannel1.SystemLoopBegin();
  BoardDeclarations::Instances::TArduinoBasicDigitalPWMChannel2.SystemLoopBegin();
  Declarations::Instances::UltrasonicRanger1.SystemLoopBegin();
  Declarations::Instances::PulseGenerator1.SystemLoopBegin();
  Declarations::Instances::PulseGenerator.SystemLoopBegin();
}





















